create database blinkend;
use blinkend;
CREATE TABLE blink (
    Item_Fat_Content          VARCHAR(20),
    Item_Identifier           VARCHAR(10),
    Item_Type                 VARCHAR(50),
    Outlet_Establishment_Year INT,
    Outlet_Identifier         VARCHAR(10),
    Outlet_Location_Type      VARCHAR(10),
    Outlet_Size               VARCHAR(10),
    Outlet_Type               VARCHAR(30),
    Item_Visibility           DECIMAL(12,8),
    Item_Weight               DECIMAL(10,4),
    Sales                     DECIMAL(12,4),
    Rating                    TINYINT
);
set sql_safe_updates=0;
select * from blink;
select count(*) from blink;

-- for item fat content
UPDATE blink
SET `Item Fat Content` = CASE
    WHEN `Item Fat Content` IN ('LF', 'low fat') THEN 'Low Fat'
    WHEN `Item Fat Content` = 'Reg' THEN 'Regular'
    ELSE `Item Fat Content`
END;

select distinct `item fat content` from blink;

-- 1)Total sales generated 
select round(sum(`sales`),2) as total_sales from blink;

select concat(cast(sum(`sales`)/1000000 as decimal(10,2)),' ','Millions') as total_sales from blink;

-- 2) average of sales
select cast(avg(sales) as decimal(10,2)) as average_sales from blink;

-- 3)Number of Items
select count(*) as number_of_items from blink;

-- 4)Total sales generated by low fat content
select round(sum(`sales`),2) as total_sales from blink
	where `item fat content`='Low fat';
    
select concat(cast(sum(`sales`)/1000000 as decimal(10,2)),' ','Millions') 
	as total_sales from blink
    where `item fat content`='Low Fat';
    
-- 4)Total sales generated by found year of 2022
select concat(cast(sum(`sales`)/1000000 as decimal(10,2)),' ','Millions') 
	as total_sales from blink
    where `outlet establishment year`=2022;
    
-- 5) average rating of blinkit
select cast(avg(rating) as decimal(10,2)) as average_rating from blink;

-- 6)Total sales by fat content
select `item fat content`,concat(cast(sum(sales)/1000000 as decimal(10,2)),' ','Millions') as total_sales,
	cast(avg(sales) as decimal(10,2)) as avg_sales,
    count(*) as no_of_items,
    cast(avg(rating) as decimal(10,2)) as average_rating 
    
	from blink where `outlet establishment year`=2022
    group by `item fat content`
    order by `total_sales`;
    
-- 7)average sales byu fat content
select `item fat content`,cast(avg(sales) as decimal(10,2)) as avg_sales
	from blink
    group by `item fat content`
    order by `avg_sales`;
    
-- 8) Total sales by item type
select `item type`,cast(sum(sales) as decimal(10,2)) as total_sales,
	cast(avg(sales) as decimal(10,2)) as avg_sales,
    count(*) as no_of_items,
    cast(avg(rating) as decimal(10,2)) as average_rating 
    from blink
    group by `item type`
    order by `total_sales` desc;
    
-- 9)fat contet by outlet for total sales 
select `outlet location type`,`item fat content`,cast(sum(sales)/1000000 as decimal(10,2)) as total_sales,
	cast(avg(sales) as decimal(10,2)) as avg_sales,
    count(*) as no_of_items,
    cast(avg(rating) as decimal(10,2)) as average_rating 
	from blink 
    group by `item fat content`,`outlet location type`
    order by `total_sales`;
    
-- 10) same as 9th one
SELECT 
    `Outlet Location Type`,
    SUM(CASE WHEN `Item Fat Content` = 'Low Fat' THEN Sales ELSE 0 END) AS Low_Fat,
    SUM(CASE WHEN `Item Fat Content` = 'Regular' THEN Sales ELSE 0 END) AS Regular
FROM blink
GROUP BY `Outlet Location Type`
ORDER BY `Outlet Location Type`;

-- 11)Toal sales by outlet establishment
select `outlet establishment year`,
cast(sum(sales) as decimal(10,2)) as total_sales,
	cast(avg(sales) as decimal(10,2)) as avg_sales,
    count(*) as no_of_items,
    cast(avg(rating) as decimal(10,2)) as average_rating
	from blink
    group by `outlet establishment year`
    order by `outlet establishment year` desc;
    
-- 12)percentage of sales by outlet size
select `outlet size`,
	cast(sum(sales) as decimal(10,2)) as total_sales,
    cast((sum(sales) * 100.0 /sum(sum(sales)) over()) as decimal (10,2)) as sales_percentage
from blink
group by `outlet size`
order by total_sales desc; 
    
-- 13) sales by outlet location
select `outlet location type`,
	cast(sum(sales) as decimal(10,2)) as total_sales,
    cast(avg(sales) as decimal(10,2)) as avg_sales,
    count(*) as no_of_items,
    cast(avg(rating) as decimal(10,2)) as average_rating,
     cast((sum(sales) * 100.0 /sum(sum(sales)) over()) as decimal (10,2)) as sales_percentage
from blink
group by `outlet location type`
order by total_sales desc; 

-- 14)all metrices by outler type
select `outlet type`,
	cast(sum(sales) as decimal(10,2)) as total_sales,
    cast(avg(sales) as decimal(10,2)) as avg_sales,
    count(*) as no_of_items,
    cast(avg(rating) as decimal(10,2)) as average_rating,
     cast((sum(sales) * 100.0 /sum(sum(sales)) over()) as decimal (10,2)) as sales_percentage
from blink
group by `outlet type`
order by total_sales desc; 
